"use client";

/**
 * NewJobModal — "The Cutting Table" (Concept 2, wired to the live API).
 *
 * ─────────────────────────────────────────────────────────────────────────
 * DATA FLOW (read this before touching anything)
 * ─────────────────────────────────────────────────────────────────────────
 *
 * The modal mirrors the three folds of the concept: 01 Client, 02 The
 * fitting, 03 The job. Everything a tailor types/taps is accumulated in
 * local state and only hits the API on "Create job". There are two submit
 * paths, and choosing the wrong one corrupts the database, so read this:
 *
 *   1. CLIENT SEARCH
 *      GET /customers is keyset-paginated by name and has NO server-side
 *      search parameter (see customers.validation.ts). A single tailor's
 *      list is small, so we fetch up to the 100-row cap once when the
 *      modal opens and filter in memory. When she outgrows 100 clients,
 *      add a ?q= search to the backend instead of paging here.
 *
 *   2. SUBJECTS ("For whom")
 *      Selecting a returning client calls GET /customers/:id/subjects
 *      (limit 100) and shows Self first, then family subjects. A brand-new
 *      client starts with a single "Self" subject. "+ Add subject" works
 *      for both: new clients keep the subject local (created inside the
 *      /jobs/new-customer transaction), while returning clients persist it
 *      immediately via POST /customers/:id/subjects on ✓ so the job can
 *      link to a real subject id.
 *
 *   3. MEASUREMENTS → jsonb
 *      Selecting a subject that already has a fitting calls
 *      GET /subjects/:id/measurements (newest first) and pre-fills the
 *      chips from the LATEST record. Edits/removals/adds are tracked in
 *      `dirtyMeas` — a touched set becomes a NEW measurements row on
 *      submit so fitting history is never mutated in place.
 *      The chips map to the jsonb the backend expects:
 *      Record<string, number> with camelCase keys ("Sleeve length" →
 *      "sleeveLength"). Keys are auto-generated by `toKey`.
 *
 *   4. SUBMIT — TWO DIFFERENT ENDPOINTS, DO NOT MIX THEM UP
 *      • New client  → POST /jobs/new-customer  (createJob)
 *        One transaction: customer + subject + measurement + job.
 *        subjects[] must contain EXACTLY ONE entry (backend enforces
 *        `.length(1)`), relationship defaults to "self", and the backend
 *        substitutes the customer's name for a self subject.
 *      • Returning client → POST /jobs/:subjectId  (createJobForSubject)
 *        NEVER /jobs/new-customer: that endpoint unconditionally INSERTs
 *        a customer row and would duplicate the client in the database.
 *        createJobForSubject requires an existing measurementId, so if
 *        the tailor touched the measurements (or the subject had none on
 *        file) we first POST /subjects/:id/measurements with today's
 *        date and use the returned id; otherwise we reuse the id of the
 *        latest saved fitting.
 *
 *   5. PHOTOS
 *      styleRef on the job schema is { url, alt }[] — the backend has no
 *      upload endpoint yet (docs plan Cloudinary later), so the picker
 *      here only PREVIEWS locally (object URLs) and the photos are NOT
 *      included in the request. Re-enable by mapping uploaded URLs into
 *      job.styleRef once uploads exist.
 *
 *   6. DUE DATE
 *      The jobs table stores a `date` column; the UI sends the explicit
 *      "YYYY-MM-DD" string from the native picker and z.coerce.date()
 *      parses it. `status` is omitted so it defaults to "pending".
 * ─────────────────────────────────────────────────────────────────────────
 */
import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useToast } from "@/components/toast";
import {
  addSubject,
  createJob,
  createJobForSubject,
  createMeasurement,
  listCustomers,
  listMeasurements,
  listSubjects,
  type Customer,
  type Job,
  type Measurement,
  type Subject,
} from "@/lib/api-client";

/* ------------------------------ helpers ------------------------------ */

const naira = new Intl.NumberFormat("en-NG", {
  style: "currency",
  currency: "NGN",
  maximumFractionDigits: 0,
});

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

/** "2026-09-24" → "24 Sep" (date strings only — no timezone drift). */
function fmtDate(value: string): string {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(value);
  if (!m) return value;
  return `${+m[3]!} ${MONTHS[+m[2]! - 1]}`;
}

function initials(name: string): string {
  return (
    name
      .split(/\s+/)
      .filter((w) => !/^(mrs|mr|ms|dr)\.?$/i.test(w))
      .slice(0, 2)
      .map((w) => w[0]?.toUpperCase() ?? "")
      .join("") || "•"
  );
}

/**
 * Common measurements — the tailor will provide her own list later; this
 * generic set keeps the composer useful until then.
 */
const COMMON_MEASUREMENTS = [
  "Bust", "Waist", "Hip", "Chest", "Shoulder", "Neck", "Armhole", "Biceps",
  "Wrist", "Sleeve length", "Dress length", "Gown length", "Blouse length",
  "Kaftan length", "Agbada length", "Boubou length", "Wrapper length",
  "Trouser waist", "Trouser length", "Inseam", "Thigh", "Calf", "Ankle",
  "Back length", "Full length", "Head",
];

/** "Sleeve length" → "sleeveLength" — the camelCase key the jsonb stores. */
function toKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, "");
}

/* Regexes mirror the backend zod schemas (customers.validation.ts). */
const NAME_RE = /^[a-zA-Z]+(?:[ '-][a-zA-Z]+)*$/;
const PHONE_RE = /^\+?[0-9]{7,15}$/;

/** One entry in the "For whom" chip row. */
interface ModalSubject {
  key: string;                 // "new" / "new-<rand>" for brand-new clients, subject.id otherwise
  subjectId?: string;          // set for subjects already in the database
  relationship: string;        // "self" | "daughter" | ... (backend defaults to "self")
  name: string;                // person's name (self subjects use the client's name)
  loaded: boolean;             // whether saved measurements were fetched for this subject
  latestMeasId?: string;       // id of the newest saved fitting — reused when untouched
}

interface PhotoPreview {
  url: string;
  alt: string;
}

const todayISO = () => new Date().toISOString().slice(0, 10);

/* ----------------------------- shared styles ----------------------------- */

const inputClass =
  "w-full rounded-xl border border-white/10 bg-white/[0.05] px-3.5 py-3 text-[13px] text-ink outline-none transition-[border-color,box-shadow] placeholder:font-light placeholder:text-stone focus:border-teal focus:shadow-[0_0_0_3px_rgba(91,124,250,0.18)]";

const chipClass =
  "inline-flex items-center gap-[7px] rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-[11px] font-medium text-ink-soft transition-all active:scale-95";

const chipOnClass =
  "border-teal bg-teal-tint text-ink shadow-[0_0_16px_-6px_rgba(91,124,250,0.7)]";

const chipAddClass =
  "border-dashed border-teal-border bg-transparent text-teal-light";

const monoClass =
  "flex h-[22px] w-[22px] flex-shrink-0 items-center justify-center rounded-full border border-teal-border bg-teal-tint text-[8.5px] font-semibold text-teal-light";

// Section titles need clear air above them — a uniform mt-6 (24px) keeps
// every title in the folds from feeling glued to the block above it.
const miniLabelClass =
  "mt-6 text-[8px] font-semibold uppercase tracking-[0.2em] text-stone";

/* --------------------------------- UI --------------------------------- */

export default function NewJobModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const queryClient = useQueryClient();
  const toast = useToast();

  /* ---------- 01 · client ---------- */
  const [customers, setCustomers] = useState<Customer[] | null>(null);
  const [query, setQuery] = useState("");
  const [ddOpen, setDdOpen] = useState(false);
  const [client, setClient] = useState<Customer | null>(null); // returning client or null = new
  const [phone, setPhone] = useState("");

  /* ---------- 02 · fitting ---------- */
  const [subjects, setSubjects] = useState<ModalSubject[]>([]);
  const [activeKey, setActiveKey] = useState("new");
  const [styles, setStyles] = useState<Record<string, string>>({});
  const [meas, setMeas] = useState<Record<string, Record<string, number | null>>>({});
  const [dirtyMeas, setDirtyMeas] = useState<Set<string>>(new Set()); // subject keys touched → new measurement row
  const [composer, setComposer] = useState("");
  const [pendingMeas, setPendingMeas] = useState<{ key: string; name: string } | null>(null);
  const [editingMeas, setEditingMeas] = useState<string | null>(null);
  const [addingSubject, setAddingSubject] = useState(false); // inline add-subject form visible
  const [subjectSaving, setSubjectSaving] = useState(false);
  const [subjectError, setSubjectError] = useState<string | null>(null);

  /* ---------- 03 · job ---------- */
  const [desc, setDesc] = useState("");
  const [price, setPrice] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [photos, setPhotos] = useState<PhotoPreview[]>([]);

  /* ---------- sheet state ---------- */
  const [fold, setFold] = useState<1 | 2 | 3>(1);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [created, setCreated] = useState<Job | null>(null);

  // Dropdowns are portaled to <body> so the fold's overflow-hidden never
  // clips them; the rect is measured from the triggering input on open.
  const ddWrapRef = useRef<HTMLDivElement>(null);
  const ddRef = useRef<HTMLDivElement>(null);
  const nameInputRef = useRef<HTMLInputElement>(null);
  const [ddRect, setDdRect] = useState<{ top: number; left: number; width: number } | null>(null);
  const compWrapRef = useRef<HTMLDivElement>(null);
  const compRef = useRef<HTMLDivElement>(null);
  const compInputRef = useRef<HTMLInputElement>(null);
  const [compRect, setCompRect] = useState<{ top: number; left: number; width: number } | null>(null);
  const [sugOpen, setSugOpen] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const activeSubject = subjects.find((s) => s.key === activeKey) ?? null;

  /* ---------- open: fetch the client list once ---------- */
  useEffect(() => {
    if (!open) return;
    // Reset to a fresh "new client" sheet every time it opens.
    setCustomers(null);
    setQuery("");
    setClient(null);
    setPhone("");
    setSubjects([{ key: "new", relationship: "self", name: "", loaded: true }]);
    setActiveKey("new");
    setStyles({});
    setMeas({});
    setDirtyMeas(new Set());
    setComposer("");
    setPendingMeas(null);
    setEditingMeas(null);
    setAddingSubject(false);
    setSubjectError(null);
    setDesc("");
    setPrice("");
    setDueDate("");
    setPhotos([]);
    setFold(1);
    setError(null);
    setCreated(null);

    // Step 1 of the data flow: GET /customers (cap 100) once, filter in
    // memory — the API has no search parameter (see file header comment).
    listCustomers({ limit: 100 })
      .then((res) => setCustomers(res.data ?? []))
      .catch(() => setCustomers([])); // search area shows a hint; new-client flow still works

    // Lock page scroll while the sheet is up.
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "";
    };
  }, [open]);

  /* Escape closes the sheet; click-outside closes the dropdowns. The
     portaled dropdowns live outside their wrappers, so both refs count. */
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    const onDown = (e: MouseEvent) => {
      const t = e.target as Node;
      if (!(ddWrapRef.current?.contains(t) || ddRef.current?.contains(t))) setDdOpen(false);
      if (!(compWrapRef.current?.contains(t) || compRef.current?.contains(t))) setSugOpen(false);
    };
    document.addEventListener("keydown", onKey);
    document.addEventListener("mousedown", onDown);
    return () => {
      document.removeEventListener("keydown", onKey);
      document.removeEventListener("mousedown", onDown);
    };
  }, [open, onClose]);

  const filteredCustomers = useMemo(() => {
    const q = query.trim().toLowerCase();
    return (customers ?? []).filter((c) => c.name.toLowerCase().includes(q));
  }, [customers, query]);

  /* ---------- client handlers ---------- */

  function clearClient() {
    setClient(null);
    setQuery("");
    setDdOpen(false);
    setAddingSubject(false);
    setSubjectError(null);
    setPhone("");
    setSubjects([{ key: "new", relationship: "self", name: "", loaded: true }]);
    setActiveKey("new");
    setMeas({});
    setDirtyMeas(new Set());
  }

  async function pickClient(c: Customer) {
    setClient(c);
    setQuery(c.name);
    setDdOpen(false);
    setAddingSubject(false);
    setSubjectError(null);
    setPhone("");
    // "For whom" is scoped to this client: GET /customers/:id/subjects,
    // Self first, then the rest in the API's newest-first order.
    const res = await listSubjects(c.id, { limit: 100 });
    const rows = (res.data ?? []).slice().sort((a, b) =>
      a.relationship === "self" ? -1 : b.relationship === "self" ? 1 : 0,
    );
    const mapped: ModalSubject[] = rows.map((s: Subject) => ({
      key: s.id,
      subjectId: s.id,
      relationship: s.relationship ?? "self",
      name: s.name,
      loaded: false, // saved measurements load lazily on first selection
    }));
    setSubjects(mapped);
    const first = mapped[0];
    setActiveKey(first?.key ?? "");
    setMeas({});
    setDirtyMeas(new Set());
    // Load the initially-selected (Self) subject's fitting too — it is
    // active without a click, so selectSubject() must be called directly.
    if (first) await selectSubject(first);
  }

  /* ---------- subject handlers ---------- */

  function startAddSubject() {
    // A pending subject (key "new-<rand>") is added for BOTH new and
    // returning clients. New clients keep it local — the backend creates
    // the row inside the /jobs/new-customer transaction. Returning clients
    // persist it on confirm via POST /customers/:id/subjects so the job
    // can link to a real subject id.
    const key = "new-" + Math.random().toString(36).slice(2, 7);
    setSubjects((prev) => [
      ...prev.filter((x) => !x.key.startsWith("new-")), // drop stale pending rows
      { key, relationship: "daughter", name: "", loaded: true },
    ]);
    setActiveKey(key);
    setAddingSubject(true);
    setSubjectError(null);
  }

  async function confirmSubject() {
    const subj = activeSubject;
    if (!subj || !subj.key.startsWith("new-")) return;
    const name = subj.name.trim();
    if (name.length < 2) {
      setSubjectError("Name needs at least 2 letters.");
      return;
    }
    setSubjectSaving(true);
    try {
      if (client) {
        // Returning client → create-subject API now, so submit step 4 can
        // use createJobForSubject(subjectId) with the real subject id.
        const res = await addSubject(client.id, {
          name,
          relationship: subj.relationship,
        });
        const created = res.data!;
        setSubjects((prev) =>
          prev.map((x) =>
            x.key === subj.key
              ? {
                  key: created.id,
                  subjectId: created.id,
                  relationship: created.relationship ?? subj.relationship,
                  name: created.name,
                  loaded: true, // brand-new subject → no saved fitting to fetch
                }
              : x,
          ),
        );
        setActiveKey(created.id);
      }
      setAddingSubject(false);
    } catch (err) {
      setSubjectError(err instanceof Error ? err.message : "Could not add the subject.");
    } finally {
      setSubjectSaving(false);
    }
  }

  function cancelSubject() {
    const next = subjects.filter((x) => !(x.key === activeKey && x.key.startsWith("new-")));
    setSubjects(next);
    setActiveKey(next[0]?.key ?? "");
    setAddingSubject(false);
    setSubjectError(null);
  }

  async function selectSubject(subj: ModalSubject) {
    setActiveKey(subj.key);
    setPendingMeas(null);
    setEditingMeas(null);

    // Returning subjects load their saved fitting lazily (step 3 of the
    // data flow): GET /subjects/:id/measurements, newest first, and the
    // latest record pre-fills the chips.
    if (!subj.subjectId || subj.loaded) return;
    const res = await listMeasurements(subj.subjectId, { limit: 1 });
    const latest: Measurement | undefined = res.data?.[0];
    setSubjects((prev) =>
      prev.map((x) =>
        x.key === subj.key
          ? { ...x, loaded: true, latestMeasId: latest?.id }
          : x,
      ),
    );
    if (latest) {
      setMeas((prev) => ({ ...prev, [subj.key]: { ...latest.measurements } }));
    }
  }

  /* ---------- measurement helpers ---------- */

  const currentMeas = () => meas[activeKey] ?? {};

  function touchMeas(next: Record<string, number | null>) {
    // Marking the subject dirty means "write a NEW measurements row on
    // submit" — history is append-only (measurements table, see header).
    setMeas((prev) => ({ ...prev, [activeKey]: next }));
    setDirtyMeas((prev) => new Set(prev).add(activeKey));
  }

  function commitPending() {
    const raw = (document.getElementById("pendVal") as HTMLInputElement | null)?.value ?? "";
    const value = Number(raw.replace(/[^\d.]/g, ""));
    if (pendingMeas && raw.trim() && !Number.isNaN(value)) {
      touchMeas({ ...currentMeas(), [pendingMeas.key]: value });
    }
    setPendingMeas(null);
  }

  function commitEdit(key: string, raw: string) {
    const value = Number(raw.replace(/[^\d.]/g, ""));
    if (raw.trim() && !Number.isNaN(value)) {
      touchMeas({ ...currentMeas(), [key]: value });
    }
    setEditingMeas(null);
  }

  /* ---------- photos (local preview only — see header step 5) ---------- */

  function onFiles(e: React.ChangeEvent<HTMLInputElement>) {
    const files = [...(e.target.files ?? [])];
    const room = 6 - photos.length;
    setPhotos((prev) => [
      ...prev,
      ...files.slice(0, Math.max(0, room)).map((f) => ({
        url: URL.createObjectURL(f),
        alt: "Style reference",
      })),
    ]);
    e.target.value = "";
  }

  /* ---------- submit: step 4 of the data flow ---------- */

  async function handleCreate() {
    setError(null);

    // ---- client-side validation mirroring the backend zod schemas ----
    const name = (client?.name ?? query).trim();
    if (name.length < 2 || !NAME_RE.test(name)) {
      setError("Name must be at least 2 letters (letters, spaces, apostrophes, hyphens only).");
      setFold(1);
      return;
    }
    if (!client && phone.trim() && !PHONE_RE.test(phone.trim())) {
      setError("Phone must be 7–15 digits, optionally starting with +.");
      setFold(1);
      return;
    }
    if (activeSubject && activeSubject.relationship !== "self" && activeSubject.name.trim().length < 2) {
      setError("Give the subject a name (at least 2 letters).");
      setFold(2);
      return;
    }
    // Returning clients must confirm a pending new subject with ✓ first —
    // an unconfirmed row has no subject id for createJobForSubject.
    if (client && activeSubject?.key.startsWith("new-")) {
      setError("Confirm the new subject (tap ✓) before creating the job.");
      setFold(2);
      return;
    }
    const measEntries = currentMeas();
    if (Object.keys(measEntries).length === 0) {
      setError("Add at least one measurement for the fitting.");
      setFold(2);
      return;
    }
    const priceNum = Number(price.replace(/[^\d.]/g, ""));
    if (!price.trim() || !Number.isFinite(priceNum) || priceNum <= 0) {
      setError("Set an agreed price for the job.");
      setFold(3);
      return;
    }

    // Shared job payload — status omitted → backend defaults to "pending".
    // dueDate sent as the explicit "YYYY-MM-DD" from the native picker.
    // The fitting style is folded into `description` ("gown · purple lace")
    // because that's the only free-text column on the job — the overview's
    // "Latest work" row shows it instead of a generic "Garment".
    const style = styles[activeKey]?.trim() ?? "";
    const description = [style, desc.trim()].filter(Boolean).join(" · ");
    const jobPayload = {
      description,
      agreedPrice: priceNum,
      ...(dueDate ? { dueDate } : {}),
    };

    setSubmitting(true);
    try {
      let job: Job;
      if (!client) {
        // NEW CLIENT → POST /jobs/new-customer: customer + subject +
        // measurement + job created atomically by the backend.
        job = (await createJob({
          customer: {
            name,
            ...(phone.trim() ? { phoneNumber: phone.trim() } : {}),
          },
          subjects: [
            {
              relationship: activeSubject!.relationship,
              // The backend derives a "self" subject's name from the
              // customer; other relationships need the person's name.
              ...(activeSubject!.relationship !== "self"
                ? { name: activeSubject!.name.trim() }
                : {}),
              measurements: measEntries,
            },
          ],
          job: jobPayload,
        })).data!;
      } else {
        // RETURNING CLIENT → POST /jobs/:subjectId (never /jobs/new-customer,
        // which would INSERT a duplicate customer row — see header step 4).
        let measurementId = activeSubject?.latestMeasId;
        if (!measurementId || dirtyMeas.has(activeKey)) {
          // Measurements were touched (or none on file): persist a NEW
          // fitting row first, then link the job to it.
          const res = await createMeasurement(activeSubject!.subjectId!, {
            measurements: measEntries,
            date: todayISO(),
          });
          measurementId = res.data!.id;
        }
        job = (await createJobForSubject(activeSubject!.subjectId!, {
          measurementId,
          job: jobPayload,
        })).data!;
      }
      setCreated(job);
      // The overview's "Latest work" reads query key ["jobs"] — refresh it
      // so the new job appears without a manual reload.
      queryClient.invalidateQueries({ queryKey: ["jobs"] });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not create the job. Try again.");
    } finally {
      setSubmitting(false);
    }
  }

  /* ---------- derived UI bits ---------- */

  const suggestions = useMemo(() => {
    const q = composer.trim().toLowerCase();
    if (!q) return [];
    const matches = COMMON_MEASUREMENTS.filter((n) => n.toLowerCase().includes(q)).slice(0, 6);
    const hasExact = matches.some((n) => n.toLowerCase() === q);
    return [
      ...matches.map((n) => ({ name: n, key: toKey(n), custom: false })),
      ...(!hasExact && q ? [{ name: composer.trim(), key: toKey(composer.trim()), custom: true }] : []),
    ];
  }, [composer]);

  const subjectLabel = (s: ModalSubject) =>
    s.relationship === "self"
      ? client?.name ?? "Self"
      : s.name || "Subject";

  const dueLabel = dueDate ? fmtDate(dueDate) : "no date";
  const clientLabel = (client?.name ?? query.trim()) || "no client yet";
  const priceNum = Number(price.replace(/[^\d.]/g, "")) || 0;
  const measCount = Object.keys(currentMeas()).length;

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-label="New job">
      {/* scrim */}
      <button
        type="button"
        aria-label="Close"
        onClick={onClose}
        className="absolute inset-0 w-full animate-fade-in bg-[rgba(5,8,18,0.55)]"
      />

      {/* bottom sheet — anchored to the phone-width column like the FAB */}
      <div className="absolute inset-x-0 bottom-0 mx-auto flex h-[92dvh] w-full max-w-[430px] animate-sheet-in flex-col overflow-hidden rounded-t-[26px] border border-b-0 border-white/10 bg-[#0D1526] shadow-[0_-30px_80px_-20px_rgba(0,0,0,0.85)]">
        {/* handle */}
        <div className="mx-auto mt-2.5 h-1 w-[38px] flex-shrink-0 rounded-full bg-white/15" aria-hidden="true" />

        {/* head */}
        <div className="flex flex-shrink-0 items-center justify-between border-b border-white/10 px-5 pb-3 pt-2">
          <h2 className="font-heading text-[22px] font-medium tracking-[-0.005em] text-ink">
            The cutting <em className="italic text-teal-light">table</em>
            <span className="ml-1.5 inline-block h-1.5 w-1.5 animate-blink rounded-full bg-amber shadow-[0_0_10px_rgba(245,184,91,0.9)]" aria-hidden="true" />
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="flex h-[30px] w-[30px] items-center justify-center rounded-full border border-white/10 bg-white/5 text-[13px] text-ink-soft transition-colors hover:text-ink"
          >
            ✕
          </button>
        </div>

        {/* folds — scrolling closes the portaled dropdowns so they never float detached */}
        <div
          className="flex-1 space-y-2.5 overflow-y-auto px-4 py-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
          onScroll={() => {
            setDdOpen(false);
            setSugOpen(false);
          }}
        >
          {/* ================= 01 · CLIENT ================= */}
          <Fold
            num={1}
            name="Client"
            summary={clientLabel === "no client yet" ? "New client" : clientLabel}
            open={fold === 1}
            onToggle={() => setFold(fold === 1 ? 2 : 1)}
          >
            <div ref={ddWrapRef} className="relative">
              <input
                ref={nameInputRef}
                className={inputClass}
                placeholder="Start typing a name…"
                value={query}
                autoComplete="off"
                onChange={(e) => {
                  setQuery(e.target.value);
                  // Diverging from the picked client drops back to "new client".
                  if (client && e.target.value !== client.name) clearClient();
                  // The dropdown only appears once she types (no open-on-focus).
                  if (e.target.value.trim()) {
                    const r = nameInputRef.current?.getBoundingClientRect();
                    if (r) setDdRect({ top: r.bottom, left: r.left, width: r.width });
                    setDdOpen(true);
                  } else {
                    setDdOpen(false);
                  }
                }}
              />
              {query && (
                <button
                  type="button"
                  aria-label="Clear client"
                  onClick={clearClient}
                  className="absolute right-3 top-1/2 flex h-5 w-5 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 text-[9px] text-ink-soft"
                >
                  ✕
                </button>
              )}

              {/* returning-client dropdown — portaled to <body> (fixed rect)
                  so the fold's overflow-hidden can't clip it. */}
              {ddOpen && ddRect && createPortal(
                <div
                  ref={ddRef}
                  onMouseDown={(e) => e.stopPropagation()}
                  className="fixed z-[70] max-h-[208px] animate-fade-in overflow-y-auto rounded-2xl border border-teal-border bg-[#111B31] p-1 shadow-[0_24px_50px_-12px_rgba(0,0,0,0.7)]"
                  style={{ top: ddRect.top + 6, left: ddRect.left, width: ddRect.width }}
                >
                  {customers === null ? (
                    <div className="px-3.5 py-3 text-[11px] text-stone">Loading clients…</div>
                  ) : filteredCustomers.length === 0 ? (
                    <div className="px-3.5 py-3 text-[11px] text-stone">
                      No match — this will be a new client.
                    </div>
                  ) : (
                    <>
                      <div className="px-2.5 pb-1 pt-1.5 text-[8px] font-semibold uppercase tracking-[0.2em] text-stone">
                        Returning clients
                      </div>
                      {filteredCustomers.map((c) => (
                        <button
                          key={c.id}
                          type="button"
                          onClick={() => pickClient(c)}
                          className="flex w-full items-center gap-2.5 rounded-[10px] px-2.5 py-2 text-left transition-colors hover:bg-teal-tint"
                        >
                          <span className="flex h-[26px] w-[26px] flex-shrink-0 items-center justify-center rounded-full border border-teal-border bg-teal-tint text-[9px] font-semibold text-teal-light">
                            {initials(c.name)}
                          </span>
                          <span className="min-w-0 flex-1">
                            <span className="block truncate text-[12px] font-medium text-ink">{c.name}</span>
                            <span className="block text-[9.5px] text-stone">
                              {c.phoneNumber ?? "no phone on file"}
                            </span>
                          </span>
                          <span className="text-[11px] text-teal-light">→</span>
                        </button>
                      ))}
                    </>
                  )}
                </div>,
                document.body,
              )}
            </div>

            {/* phone — only when the client has none on file */}
            {(!client || !client.phoneNumber) && (
              <input
                className={`${inputClass} mt-2`}
                placeholder="Phone (optional)"
                value={phone}
                autoComplete="off"
                inputMode="tel"
                onChange={(e) => setPhone(e.target.value)}
              />
            )}
            {client?.phoneNumber && (
              <div className="mt-2 flex items-center gap-1.5 text-[10.5px] text-stone">
                <span className="h-1.5 w-1.5 rounded-full bg-mint shadow-[0_0_8px_rgba(62,213,152,0.8)]" aria-hidden="true" />
                Phone on file · <b className="font-medium tracking-[0.04em] text-ink-soft">{client.phoneNumber}</b>
              </div>
            )}
          </Fold>

          {/* ================= 02 · THE FITTING ================= */}
          <Fold
            num={2}
            name="The fitting"
            summary={activeSubject ? `${subjectLabel(activeSubject)}${styles[activeKey] ? " · " + styles[activeKey] : ""}` : "Who is it for?"}
            open={fold === 2}
            onToggle={() => setFold(fold === 2 ? 3 : 2)}
          >
            <div className={miniLabelClass}>For whom</div>
            <div className="flex flex-wrap gap-[7px] pt-2">
              {subjects.map((s) => (
                <button
                  key={s.key}
                  type="button"
                  onClick={() => selectSubject(s)}
                  className={`${chipClass} ${activeKey === s.key ? chipOnClass : ""}`}
                >
                  <span className={monoClass}>{initials(subjectLabel(s))}</span>
                  {subjectLabel(s)}
                  {s.relationship !== "self" && (
                    <span className="text-[9px] text-stone">{s.relationship}</span>
                  )}
                  {s.loaded && s.latestMeasId && (
                    <span className="text-[9px] text-stone">· fitted</span>
                  )}
                </button>
              ))}
              {!addingSubject && (
                <button type="button" onClick={startAddSubject} className={`${chipClass} ${chipAddClass}`}>
                  + Add subject
                </button>
              )}
            </div>

            {/* add-subject inline form — new clients keep it local, returning
                clients persist via POST /customers/:id/subjects on ✓ */}
            {addingSubject && activeSubject?.key.startsWith("new-") && (
              <div className="mt-2.5 animate-fade-in">
                <div className="flex items-center gap-2">
                  <select
                    className="flex-shrink-0 rounded-[10px] border border-white/10 bg-white/5 px-2 py-2 text-[11px] text-ink outline-none"
                    value={activeSubject.relationship}
                    onChange={(e) =>
                      setSubjects((prev) =>
                        prev.map((x) => (x.key === activeKey ? { ...x, relationship: e.target.value } : x)),
                      )
                    }
                  >
                    {["daughter","son","husband","wife","mother","father","brother","sister","other"].map((r) => (
                      <option key={r} value={r}>{r}</option>
                    ))}
                  </select>
                  <input
                    className={`${inputClass} !py-2 text-[12px]`}
                    placeholder="Name"
                    value={activeSubject.name}
                    disabled={subjectSaving}
                    onChange={(e) => {
                      setSubjectError(null);
                      setSubjects((prev) =>
                        prev.map((x) => (x.key === activeKey ? { ...x, name: e.target.value } : x)),
                      );
                    }}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") confirmSubject();
                    }}
                  />
                  <button
                    type="button"
                    aria-label="Add subject"
                    disabled={subjectSaving}
                    onClick={confirmSubject}
                    className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-[10px] bg-teal text-white shadow-[0_8px_18px_-8px_rgba(91,124,250,0.8)] transition-all hover:bg-teal-deep active:scale-95 disabled:opacity-60"
                  >
                    {subjectSaving ? (
                      <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-white/30 border-t-white" aria-hidden="true" />
                    ) : (
                      <CheckIcon />
                    )}
                  </button>
                  <button
                    type="button"
                    aria-label="Cancel add subject"
                    onClick={cancelSubject}
                    className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-[10px] border border-white/10 bg-white/5 text-[10px] text-ink-soft transition-colors hover:text-ink"
                  >
                    ✕
                  </button>
                </div>
                {subjectError && (
                  <p className="mt-1.5 text-[10px] text-rose">{subjectError}</p>
                )}
              </div>
            )}

            <div className={miniLabelClass}>Style</div>
            <input
              className={inputClass}
              placeholder="e.g. gown, maxi, blouse"
              value={styles[activeKey] ?? ""}
              onChange={(e) => setStyles((prev) => ({ ...prev, [activeKey]: e.target.value }))}
            />

            <div className={miniLabelClass}>
              Measurements <span className="font-normal normal-case tracking-[0.04em] text-stone">· cm</span>
            </div>
            <div className="flex flex-wrap gap-[7px] pt-2">
              {Object.entries(currentMeas()).map(([key, value]) =>
                editingMeas === key ? (
                  <div key={key} className="flex items-center gap-2 rounded-full border border-teal bg-teal-tint py-1.5 pl-3 pr-1.5">
                    <span className="text-[11px] font-medium text-teal-light">{key}</span>
                    <input
                      id="editVal"
                      className="w-[52px] rounded-lg border border-white/10 bg-white/5 py-1 text-center text-[12px] font-medium text-ink outline-none"
                      inputMode="decimal"
                      defaultValue={String(value ?? "")}
                      autoFocus
                      onKeyDown={(e) => {
                        if (e.key === "Enter") commitEdit(key, (e.target as HTMLInputElement).value);
                      }}
                      onBlur={(e) => commitEdit(key, e.target.value)}
                    />
                    <span className="text-[9px] text-stone">cm</span>
                    <button
                      type="button"
                      aria-label="Save"
                      className="flex h-6 w-6 items-center justify-center rounded-lg bg-mint text-[#05261A] shadow-[0_8px_16px_-8px_rgba(62,213,152,0.8)]"
                      onClick={() => commitEdit(key, (document.getElementById("editVal") as HTMLInputElement)?.value ?? "")}
                    >
                      <CheckIcon />
                    </button>
                  </div>
                ) : (
                  <button
                    key={key}
                    type="button"
                    title="Tap to update"
                    onClick={() => setEditingMeas(key)}
                    className={`${chipClass} ${chipOnClass} !px-2.5 !py-1.5`}
                  >
                    <span className={monoClass}>{key.slice(0, 2).toUpperCase()}</span>
                    {key} <b className="font-semibold text-ink">{value}</b>
                    <span className="text-[8.5px] text-stone">cm</span>
                    <span
                      aria-label={`Remove ${key}`}
                      onClick={(e) => {
                        e.stopPropagation();
                        const next = { ...currentMeas() };
                        delete next[key];
                        touchMeas(next);
                      }}
                      className="flex h-[15px] w-[15px] items-center justify-center rounded-full bg-white/5 text-[8px] text-stone hover:text-rose"
                    >
                      ✕
                    </span>
                  </button>
                ),
              )}
            </div>

            {/* composer: type → suggestion → just the value */}
            <div ref={compWrapRef} className="relative mt-2.5">
              <input
                ref={compInputRef}
                className={inputClass}
                placeholder="Type a measurement…"
                value={composer}
                onChange={(e) => {
                  setComposer(e.target.value);
                  setPendingMeas(null);
                  // Suggestions only appear after typing (portaled, see below).
                  if (e.target.value.trim()) {
                    const r = compInputRef.current?.getBoundingClientRect();
                    if (r) setCompRect({ top: r.bottom, left: r.left, width: r.width });
                    setSugOpen(true);
                  } else {
                    setSugOpen(false);
                  }
                }}
              />
              {sugOpen && composer.trim() && compRect && createPortal(
                <div
                  ref={compRef}
                  onMouseDown={(e) => e.stopPropagation()}
                  className="fixed z-[70] max-h-[172px] animate-fade-in overflow-y-auto rounded-2xl border border-teal-border bg-[#111B31] p-1 shadow-[0_20px_44px_-12px_rgba(0,0,0,0.7)]"
                  style={{ top: compRect.top + 6, left: compRect.left, width: compRect.width }}
                >
                  {suggestions.map((s) => (
                    <button
                      key={s.key + (s.custom ? "-c" : "")}
                      type="button"
                      onClick={() => {
                        // Already present → jump straight into editing it.
                        if (Object.prototype.hasOwnProperty.call(currentMeas(), s.key)) {
                          setEditingMeas(s.key);
                        } else {
                          setPendingMeas({ key: s.key, name: s.name });
                        }
                        setComposer("");
                        setSugOpen(false);
                      }}
                      className={`flex w-full items-center justify-between rounded-[9px] px-2.5 py-2 text-left text-[11.5px] transition-colors hover:bg-teal-tint hover:text-ink ${
                        s.custom ? "text-teal-light" : "text-ink-soft"
                      }`}
                    >
                      <span>{s.custom ? `Use "${s.name}"` : s.name}</span>
                      <span className="font-mono text-[8.5px] text-stone">{s.key}</span>
                    </button>
                  ))}
                </div>,
                document.body,
              )}
            </div>

            {/* pending value entry for a tapped suggestion */}
            {pendingMeas && (
              <div className="mt-2 flex animate-fade-in items-center gap-2 rounded-xl border border-teal-border bg-teal-tint p-2">
                <span className="flex-shrink-0 text-[11px] font-semibold text-teal-light">{pendingMeas.name}</span>
                <span className="flex-shrink-0 font-mono text-[8px] text-stone">{pendingMeas.key}</span>
                <input
                  id="pendVal"
                  className="min-w-0 flex-1 rounded-[9px] border border-white/10 bg-white/5 px-2.5 py-1.5 text-[13px] font-medium text-ink outline-none"
                  inputMode="decimal"
                  placeholder="0"
                  autoFocus
                  onKeyDown={(e) => {
                    if (e.key === "Enter") commitPending();
                  }}
                />
                <span className="text-[9px] text-stone">cm</span>
                <button type="button" aria-label="Add value" onClick={commitPending} className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-[9px] bg-mint text-[#05261A] shadow-[0_8px_16px_-8px_rgba(62,213,152,0.8)]">
                  <CheckIcon />
                </button>
              </div>
            )}

            {/* The measurements are grouped into the camelCase key-value
                jsonb object internally (see `touchMeas` + the header data
                flow) — no need to show that to the tailor. */}
          </Fold>

          {/* ================= 03 · THE JOB ================= */}
          <Fold
            num={3}
            name="The job"
            summary={priceNum > 0 ? naira.format(priceNum) : "Set the price"}
            open={fold === 3}
            onToggle={() => setFold(fold === 3 ? 1 : 3)}
          >
            <input
              className={inputClass}
              placeholder="Description — e.g. purple lace, puff sleeves"
              value={desc}
              onChange={(e) => setDesc(e.target.value)}
            />
            <div className={miniLabelClass}>Agreed price</div>
            <div className="relative">
              <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[13px] font-medium text-teal-light">₦</span>
              <input
                className={`${inputClass} !pl-8 !text-[17px] !font-semibold`}
                placeholder="0"
                inputMode="numeric"
                value={price}
                onChange={(e) => setPrice(e.target.value)}
              />
            </div>
            <div className={miniLabelClass}>Due date</div>
            <div className="relative">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" className="pointer-events-none absolute left-3.5 top-1/2 h-[14px] w-[14px] -translate-y-1/2 text-teal-light">
                <rect x="3.5" y="5" width="17" height="16" rx="3" /><path d="M3.5 10h17" /><path d="M8 3v4" /><path d="M16 3v4" />
              </svg>
              <input
                type="date"
                className={`${inputClass} !pl-9 [color-scheme:dark]`}
                value={dueDate}
                min={todayISO()}
                onChange={(e) => setDueDate(e.target.value)}
              />
            </div>
            <div className={miniLabelClass}>Style reference</div>
            <div className="flex flex-wrap gap-2 pt-1">
              {photos.map((p, i) => (
                <div key={p.url} className="relative h-14 w-14 flex-shrink-0 overflow-visible rounded-[13px] border border-teal-border bg-teal-tint">
                  <img src={p.url} alt={p.alt} className="h-full w-full rounded-[11px] object-cover" />
                  <button
                    type="button"
                    aria-label="Remove photo"
                    onClick={() => setPhotos((prev) => prev.filter((_, j) => j !== i))}
                    className="absolute -right-1.5 -top-1.5 flex h-[17px] w-[17px] items-center justify-center rounded-full border border-rose/50 bg-[#241019] text-[8px] text-rose shadow-[0_4px_10px_-2px_rgba(0,0,0,0.6)]"
                  >
                    ✕
                  </button>
                </div>
              ))}
              {photos.length < 6 && (
                <button
                  type="button"
                  aria-label="Add photo"
                  onClick={() => fileRef.current?.click()}
                  className="flex h-14 w-14 flex-shrink-0 items-center justify-center rounded-[13px] border-[1.5px] border-dashed border-teal-border bg-white/[0.03] text-teal-light transition-transform active:scale-95"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" className="h-[17px] w-[17px]">
                    <path d="M12 5v14" /><path d="M5 12h14" />
                  </svg>
                </button>
              )}
            </div>
            <div className="mt-1.5 text-[9px] text-stone">
              Local preview only — Cloudinary upload comes later; photos are not sent with the job until then.
            </div>
            <input ref={fileRef} type="file" accept="image/*" multiple hidden onChange={onFiles} />
          </Fold>
        </div>

        {/* error line */}
        {error && (
          <div className="flex-shrink-0 px-4 pb-2">
            <p className="animate-shake rounded-xl border border-rose/25 bg-rose/10 px-3.5 py-2.5 text-[11.5px] text-rose">{error}</p>
          </div>
        )}

        {/* live ticket footer */}
        <div className="flex flex-shrink-0 items-center gap-3 border-t border-white/10 bg-[#0D1526] px-4 pb-4 pt-3">
          <div className="min-w-0 flex-1">
            <div className="mb-1 text-[7.5px] font-semibold uppercase tracking-[0.22em] text-stone">Ticket</div>
            <div className="whitespace-nowrap text-[20px] font-bold leading-none tracking-[-0.02em] text-ink">
              <small className="mr-0.5 text-[12px] font-medium text-teal-light">₦</small>
              {priceNum.toLocaleString("en-US")}
            </div>
            <div className="mt-1 truncate whitespace-nowrap text-[9px] text-stone">
              due <b className="font-semibold text-amber">{dueLabel}</b> · {clientLabel}
            </div>
          </div>
          <button
            type="button"
            onClick={handleCreate}
            disabled={submitting}
            className="flex flex-shrink-0 items-center gap-2 rounded-2xl bg-teal px-5 py-3.5 text-[12.5px] font-semibold text-white shadow-[0_12px_26px_-10px_rgba(91,124,250,0.8)] transition-all hover:bg-teal-deep active:scale-95 disabled:opacity-60"
          >
            {submitting ? (
              <span className="h-[15px] w-[15px] animate-spin rounded-full border-2 border-white/30 border-t-white" aria-hidden="true" />
            ) : (
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" className="h-[15px] w-[15px]">
                <path d="M12 5v14" /><path d="M5 12h14" />
              </svg>
            )}
            {submitting ? "Creating…" : "Create job"}
          </button>
        </div>

        {/* success overlay */}
        {created && (
          <div className="absolute inset-0 z-40 flex animate-fade-in flex-col items-center justify-center rounded-t-[26px] bg-[#0D1526] px-8 text-center">
            <div className="mb-4 flex h-[62px] w-[62px] items-center justify-center rounded-full border border-mint/40 bg-mint/10 shadow-[0_0_30px_-8px_rgba(62,213,152,0.7)]">
              <svg viewBox="0 0 24 24" fill="none" stroke="#3ED598" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" className="h-[26px] w-[26px]">
                <path d="M4.5 12.5 9.5 17.5 19.5 6.5" />
              </svg>
            </div>
            <h3 className="font-heading text-[22px] font-medium text-ink">
              Cut and <em className="italic text-mint">pinned</em>.
            </h3>
            <p className="mt-1.5 text-[11.5px] leading-relaxed text-ink-soft">
              {styles[activeKey] || "Garment"} for {subjectLabel(activeSubject!)} — {naira.format(created.agreedPrice)}.
            </p>
            <div className="mt-3.5 w-full rounded-[13px] border border-white/10 bg-white/[0.04] px-3.5 py-3 text-left">
              <div className="flex items-baseline justify-between text-[13px] font-semibold">
                <span className="truncate">{clientLabel} · {subjectLabel(activeSubject!)} · {styles[activeKey] || "—"}</span>
                <span className="ml-3 flex-shrink-0 text-teal-light">{naira.format(created.agreedPrice)}</span>
              </div>
              <div className="mt-1 text-[9.5px] text-stone">
                due {created.dueDate ? fmtDate(created.dueDate) : "no date"} · {measCount} measurement{measCount === 1 ? "" : "s"} saved
              </div>
            </div>
            <div className="mt-4 flex w-full gap-2.5">
              <button
                type="button"
                onClick={() => {
                  // The in-sheet confirmation closes; the toast keeps the
                  // confirmation alive over the overview.
                  toast.show({
                    title: "Cut and pinned.",
                    detail: `${clientLabel} · ${styles[activeKey] || "garment"} — ${naira.format(created.agreedPrice)}${created.dueDate ? `, due ${fmtDate(created.dueDate)}` : ""}`,
                  });
                  onClose();
                }}
                className="flex-1 rounded-[13px] border border-white/10 bg-white/5 py-3 text-[11.5px] font-semibold text-ink-soft transition-colors hover:text-ink"
              >
                Done
              </button>
              <button
                type="button"
                onClick={() => {
                  toast.show({
                    title: "Cut and pinned.",
                    detail: `${clientLabel} · ${styles[activeKey] || "garment"} — ${naira.format(created.agreedPrice)}${created.dueDate ? `, due ${fmtDate(created.dueDate)}` : ""}`,
                  });
                  onClose();
                }}
                className="flex-1 rounded-[13px] bg-teal py-3 text-[11.5px] font-semibold text-white shadow-[0_12px_26px_-10px_rgba(91,124,250,0.8)] transition-colors hover:bg-teal-deep"
              >
                View job
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/* ------------------------------- pieces ------------------------------- */

function Fold({
  num,
  name,
  summary,
  open,
  onToggle,
  children,
}: {
  num: number;
  name: string;
  summary: string;
  open: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <section className={`overflow-hidden rounded-[18px] border border-white/10 bg-white/[0.03] transition-colors ${open ? "border-teal/35" : ""}`}>
      <button type="button" onClick={onToggle} className="flex w-full items-center gap-3 px-4 py-3.5">
        <span className={`w-6 flex-shrink-0 text-right font-heading text-[15px] italic transition-colors ${open ? "text-teal-light" : "text-stone"}`}>
          {num}
        </span>
        <span className="flex-1 text-left text-[13.5px] font-semibold tracking-[0.01em] text-ink">{name}</span>
        <span className="max-w-[110px] truncate text-[9.5px] text-stone">{summary}</span>
        <span className={`flex h-[22px] w-[22px] flex-shrink-0 items-center justify-center rounded-full border border-white/10 bg-white/5 text-ink-soft transition-transform duration-300 ${open ? "rotate-180 text-teal-light" : ""}`}>
          <svg viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" className="h-2.5 w-2.5">
            <path d="M1.5 3.5 5 7l3.5-3.5" />
          </svg>
        </span>
      </button>
      {/* grid-rows trick gives a smooth height collapse without measuring */}
      <div className={`grid transition-[grid-template-rows] duration-300 ease-out ${open ? "grid-rows-[1fr]" : "grid-rows-[0fr]"}`}>
        <div className="min-h-0 overflow-hidden">
          <div className="px-4 pb-4 pt-1">{children}</div>
        </div>
      </div>
    </section>
  );
}

function CheckIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" className="h-3 w-3">
      <path d="M5 12.5 10 17.5 19 6.5" />
    </svg>
  );
}